import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Identity Documents',items:['Original passport with at least 6 months validity from the intended date of travel.','Clear photocopy of the passport bio page and all previous visas.','Copies of previous passports (if applicable).']},
 {n:'02',title:'Photograph & Application',items:['Recent passport-size colour photograph as per Canadian visa specifications.','Completed Canada Visitor Visa (Temporary Resident Visa) application form.','Biometrics appointment confirmation (if applicable).']},
 {n:'03',title:'Employment / Business Documents',items:['Company covering letter mentioning designation, salary, purpose of visit, and approved leave.','Employment ID card or appointment letter.','For self-employed applicants: GST Registration, Company Registration Certificate, Partnership Deed, or Business Proof.']},
 {n:'04',title:'Financial Documents',items:['Personal bank statements for the last 6 months with sufficient balance.','Income Tax Returns (ITR) for the last 2–3 assessment years.','Salary slips for the last 3 months or proof of regular income.']},
 {n:'05',title:'Travel Documents',items:['Detailed travel itinerary.','Hotel reservation or accommodation confirmation.','Return flight reservation (if applicable).']},
 {n:'06',title:'Supporting Documents',items:['Invitation letter from relatives or friends in Canada (if applicable).','Proof of relationship with the inviter (if visiting family).','Any additional supporting documents requested by Immigration, Refugees and Citizenship Canada (IRCC).']}
];
export default function CanadaVisa(){
 return <><SEO title="Canada Tourist Visa Assistance" description="Canada tourist visa documentation assistance from Tourswale with ₹13,500 onwards visa charges and 25–45 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'Canada Tourist Visa Assistance',offers:{'@type':'Offer',price:'13500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero canada-visa-hero"><div><Breadcrumbs items={['Visa Services','Canada Tourist Visa']}/><span className="eyebrow">Fast • Reliable • Hassle-Free</span><h1>Canada<br/>Tourist Visa</h1><p>Professional assistance for Indian travellers visiting Canada for tourism, family visits, sightseeing, and short-term leisure travel with complete visa documentation guidance.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>25–45 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹13,500 onwards</strong><small>Subject to visa category and fees</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Tourist visa checklist</span><h2>Documents Required</h2></div><p>Prepare complete and accurate documents supporting your travel purpose, financial capability, employment or business status, and intention to return to India. Immigration, Refugees and Citizenship Canada (IRCC) may request additional documentation or biometrics based on the applicant's profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>25–45 Working Days</h2><p>Processing periods are approximate and may vary depending on IRCC processing times and applicant profile.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of Immigration, Refugees and Citizenship Canada (IRCC). Submission of complete documents does not guarantee visa approval.</p><p>Visa fees, processing timelines, biometric requirements, documentation requirements, and entry regulations are subject to change without prior notice. Applicants are advised to reconfirm the latest requirements before submission.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your Canada Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your Canada Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}
