import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Identity Documents',items:['Original passport with at least 6 months validity and at least two blank visa pages.','Clear photocopy of the passport bio page.','Copies of previous Chinese visas (if applicable).']},
 {n:'02',title:'Photograph & Application',items:['Recent passport-size colour photograph as per Chinese visa specifications.','Completed China Tourist Visa application form.','Appointment confirmation, if applicable.']},
 {n:'03',title:'Employment / Business Documents',items:['Company covering letter mentioning designation, purpose of travel, and approved leave.','Employment ID card or employment proof.','For self-employed applicants: GST Registration, Company Registration Certificate, or Business Proof.']},
 {n:'04',title:'Financial Documents',items:['Personal bank statements for the last 6 months.','Income Tax Returns (ITR) for the last 2–3 assessment years.','Salary slips for the last 3 months or proof of regular income.']},
 {n:'05',title:'Travel Documents',items:['Confirmed return flight reservation.','Hotel booking or accommodation confirmation.','Detailed day-wise travel itinerary.']},
 {n:'06',title:'Supporting Documents',items:['Invitation letter from a host in China (if applicable).','Proof of relationship with the inviter (if visiting family or friends).','Any additional supporting documents requested by the Chinese Embassy or Visa Application Service Centre.']}
];
export default function ChinaVisa(){
 return <><SEO title="China Tourist Visa Assistance" description="China tourist visa documentation assistance from Tourswale with ₹7,500 onwards visa charges and 7–10 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'China Tourist Visa Assistance',offers:{'@type':'Offer',price:'7500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero china-visa-hero"><div><Breadcrumbs items={['Visa Services','China Tourist Visa']}/><span className="eyebrow">Fast • Reliable • Hassle-Free</span><h1>China<br/>Tourist Visa</h1><p>Professional assistance for Indian travellers visiting China for tourism, family visits, sightseeing, and short-term leisure travel with complete visa documentation guidance.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>7–10 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹7,500 onwards</strong><small>Subject to visa category and fees</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Tourist visa checklist</span><h2>Documents Required</h2></div><p>Prepare complete and accurate documents supporting your travel purpose, financial capability, accommodation, and return plans. The Chinese Embassy or Visa Application Service Centre may request additional documentation depending on the applicant's profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>7–10 Working Days</h2><p>Processing periods are approximate and may vary depending on the Chinese Visa Application Service Centre and applicant profile.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the Chinese Embassy or the Chinese Visa Application Service Centre. Submission of complete documents does not guarantee visa approval.</p><p>Visa fees, processing timelines, documentation requirements, biometric requirements, and entry regulations are subject to change without prior notice. Applicants are advised to reconfirm the latest requirements before submission.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your China Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your China Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}
