import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Identity Documents',items:['Original passport with at least 6 months validity from the intended date of entry into the UAE.','Clear scanned copy of the passport bio page.','Copies of previous UAE visas (if applicable).']},
 {n:'02',title:'Photograph & Application',items:['Recent passport-size colour photograph with a white background as per UAE visa specifications.','Completed UAE Tourist Visa application form.','Signed declaration form (if applicable).']},
 {n:'03',title:'Employment / Business Documents',items:['Company covering letter mentioning designation, salary, purpose of travel, and approved leave (if applicable).','Employment ID card or employment proof.','For self-employed applicants: GST Registration, Company Registration Certificate, Partnership Deed, or Business Proof (if applicable).']},
 {n:'04',title:'Financial Documents',items:['Personal bank statements for the last 3–6 months (if requested).','Income Tax Returns (ITR) or proof of income (if applicable).','Proof of sufficient funds for the duration of the stay.']},
 {n:'05',title:'Travel Documents',items:['Confirmed return flight reservation.','Hotel booking or accommodation confirmation.','Detailed travel itinerary.','Confirmed travel dates matching the visa application.']},
 {n:'06',title:'Supporting Documents',items:['Invitation letter from a host or sponsor in the UAE (if applicable).','Proof of relationship with the inviter (if visiting family or friends).','Personal cover letter explaining the purpose of travel (if requested).','Any additional supporting documents requested by UAE Immigration.']}
];
export default function DubaiVisa(){
 return <><SEO title="Dubai (UAE) Tourist Visa Assistance" description="Dubai (UAE) tourist visa documentation assistance from Tourswale with ₹7,500 onwards visa charges and 3–5 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'Dubai (UAE) Tourist Visa Assistance',offers:{'@type':'Offer',price:'7500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero dubai-visa-hero"><div><Breadcrumbs items={['Visa Services','Dubai (UAE) Tourist Visa']}/><span className="eyebrow">Fast • Reliable • Hassle-Free</span><h1>Dubai (UAE)<br/>Tourist Visa</h1><p>Professional assistance for Indian travellers visiting Dubai and the United Arab Emirates (UAE) for tourism, family visits, sightseeing, shopping, business leisure, and short-term holidays with complete visa documentation guidance.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>3–5 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹7,500 onwards</strong><small>Subject to visa category and fees</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Tourist visa checklist</span><h2>Documents Required</h2></div><p>Prepare complete and accurate documents supporting your travel purpose, identity, accommodation, and return plans. UAE Immigration authorities may request additional documentation depending on the applicant's profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>3–5 Working Days</h2><p>Processing periods are approximate and may vary depending on UAE Immigration and applicant profile.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the UAE Immigration authorities. Submission of complete documents does not guarantee visa approval.</p><p>Visa fees, processing timelines, documentation requirements, visa validity, stay duration, and entry regulations are subject to change without prior notice. Applicants are advised to reconfirm the latest requirements before submission.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your Dubai Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your Dubai Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}
