import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Copies',items:['Original old and new passports','Current passport valid for at least six months','Two sets of the first and last passport pages']},
 {n:'02',title:'Photograph & Form',items:['One recent 2 × 2-inch photograph','White background','Completed visa application form with all details']},
 {n:'03',title:'Company Covering Letter',items:['Original letter on company letterhead','Applicant’s name and passport number','Travel date and purpose of travel','Expense details and other relevant information']},
 {n:'04',title:'Indian Company Documents',items:['Company registration certificate copy','Supporting business information if requested']},
 {n:'05',title:'Japanese Company Documents',items:['Invitation letter, signed and sealed','Letter of guarantee, signed and sealed','Day-to-day schedule of stay, signed and sealed']},
 {n:'06',title:'Additional Documents',items:['Personal income-tax returns for the last three years','Air-ticket reservation','Bank statements for the last three months']}
];
export default function JapanBusinessVisa(){
 return <><SEO title="Japan Business Visa Assistance" description="Japan business visa documentation assistance from Tourswale with ₹5,500 visa charges and 10–13 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'Japan Business Visa Assistance',offers:{'@type':'Offer',price:'5500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero japan-visa-hero"><div><Breadcrumbs items={['Visa Services','Japan Business Visa']}/><span className="eyebrow">Fast · Reliable · Hassle-Free</span><h1>Japan<br/>Business Visa</h1><p>Structured documentation guidance for Indian business travellers visiting Japan for meetings, commercial activity and professional engagements.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>10–13 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹5,500</strong><small>Per person</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Business visa checklist</span><h2>Documents Required</h2></div><p>Prepare clear and current documents from both the Indian applicant/company and the inviting Japanese company. Additional documentation may be requested based on the application profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>10–13 Working Days</h2><p>Processing periods are approximate and may vary depending on embassy review, holidays, appointment availability and individual circumstances.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the Embassy or Consulate of Japan and the applicable immigration authorities. Complete documents do not guarantee approval.</p><p>Visa charges and requirements should be reconfirmed before submission because consular policies can change.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your Business Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your Japan Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}