import {Check,FileText,IdCard,RefreshCw,ShieldCheck,MessageCircle,Phone,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const documents=[['Aadhaar Card','Current identity and address document'],['PAN Card','Clear copy of the applicant’s PAN card'],['Bank Passbook','Passbook with photograph and bank stamp'],['Education Certificate','10th-standard certificate or higher qualification'],['Birth Certificate','Required for applicants below 18 years'],['Parents’ Address Proof','Applicable for minor applicants'],['Electricity Bill','Recent light or electricity bill as address support'],['Old Passport','Required when applying for passport renewal']];
export default function Passport(){
 return <><SEO title="Fresh Passport & Passport Renewal Assistance" description="Tourswale provides document guidance for fresh passport applications and passport renewals in Navi Mumbai." schema={{'@context':'https://schema.org','@type':'Service',name:'Passport Application Assistance',provider:{'@type':'TravelAgency',name:'Tourswale'},areaServed:'Navi Mumbai, India'}}/>
 <section className="passport-hero"><div><Breadcrumbs items={['Passport Services']}/><span className="eyebrow">Fast · Reliable · Hassle-Free</span><h1>Passport<br/>Services</h1><p>Clear document guidance for fresh passport applications and passport renewals, supported by the Tourswale team.</p><div className="passport-options"><span><IdCard/>Fresh Passport</span><span><RefreshCw/>Passport Renewal</span></div><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> WhatsApp for Details</a><a className="button light" href="tel:+919987561143"><Phone/> Call Now</a></div></div><aside><ShieldCheck/><span>Your passport to</span><strong>Global Opportunities</strong><p>Documentation support from enquiry to appointment preparation.</p></aside></section>
 <section className="section passport-intro"><div><span className="eyebrow dark-eye">Application checklist</span><h2>Documents Required</h2></div><p>Requirements may vary based on applicant age, address, application category and current Passport Seva rules. Bring clear, valid originals and copies for verification guidance.</p></section>
 <section className="section ivory"><div className="passport-docs">{documents.map(([title,text],i)=><article key={title}><b>{String(i+1).padStart(2,'0')}</b><FileText/><h3>{title}</h3><p>{text}</p><Check/></article>)}</div></section>
 <section className="passport-note"><ShieldCheck/><div><span>Important information</span><h2>Assistance You Can Rely On</h2><p>Tourswale provides documentation and application guidance. Passport issuance, police verification, appointment availability and processing timelines are controlled solely by the relevant Government of India authorities.</p></div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">WhatsApp for more details</span><h2>Start Your Passport Application.</h2><p>Speak with our team before sharing documents. We’ll explain the applicable checklist and next steps.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}