import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Identity Documents',items:['Original passport with at least 6 months validity from the intended date of entry into Saudi Arabia.','Clear copy of the passport bio page.','Copies of previous Saudi visas (if applicable).']},
 {n:'02',title:'Photograph & Application',items:['Recent passport-size colour photograph with a white background as per Saudi visa specifications.','Completed Saudi Arabia Tourist Visa application form (or eVisa application, where applicable).','Signed declaration form (if applicable).']},
 {n:'03',title:'Employment / Business Documents',items:['Company covering letter mentioning designation, salary, purpose of travel, and approved leave.','Employment ID card or employment proof.','For self-employed applicants: GST Registration, Company Registration Certificate, Partnership Deed, or Business Proof.']},
 {n:'04',title:'Financial Documents',items:['Personal bank statements for the last 6 months.','Income Tax Returns (ITR) for the last 2–3 assessment years.','Salary slips for the last 3 months or proof of regular income.','Proof of sufficient funds for the duration of the stay.']},
 {n:'05',title:'Travel Documents',items:['Confirmed return flight reservation.','Hotel booking or accommodation confirmation.','Detailed travel itinerary.','Proof of onward or return travel.']},
 {n:'06',title:'Supporting Documents',items:['Invitation letter from a host in Saudi Arabia (if applicable).','Proof of relationship with the inviter (if visiting family or friends).','Personal cover letter explaining the purpose of travel.','Any additional supporting documents requested by the Saudi Ministry of Foreign Affairs or immigration authorities.']}
];
export default function SaudiArabiaVisa(){
 return <><SEO title="Saudi Arabia Tourist Visa Assistance" description="Saudi Arabia tourist visa documentation assistance from Tourswale with ₹8,500 onwards visa charges and 3–7 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'Saudi Arabia Tourist Visa Assistance',offers:{'@type':'Offer',price:'8500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero saudi-visa-hero"><div><Breadcrumbs items={['Visa Services','Saudi Arabia Tourist Visa']}/><span className="eyebrow">Fast • Reliable • Hassle-Free</span><h1>Saudi Arabia<br/>Tourist Visa</h1><p>Professional assistance for Indian travellers visiting Saudi Arabia for tourism, family visits, cultural experiences, sightseeing, leisure travel, and short-term holidays with complete visa documentation guidance.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>3–7 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹8,500 onwards</strong><small>Subject to visa category and fees</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Tourist visa checklist</span><h2>Documents Required</h2></div><p>Prepare complete and accurate documents supporting your travel purpose, financial capability, accommodation, and return plans. Saudi authorities may request additional documentation depending on the applicant's profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>3–7 Working Days</h2><p>Processing periods are approximate and may vary depending on the Saudi Ministry of Foreign Affairs and applicant profile.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the Saudi Ministry of Foreign Affairs and immigration authorities. Submission of complete documents does not guarantee visa approval.</p><p>Visa fees, processing timelines, documentation requirements, travel regulations, health requirements, and entry policies are subject to change without prior notice. Applicants are advised to reconfirm the latest requirements before submission.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your Saudi Arabia Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your Saudi Arabia Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}
