import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Globe2,Info} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport & Identity Documents',items:['Original passport with at least 6 months validity from the date of travel.','Passport issued within the last 10 years.','Minimum two blank visa pages.','Clear photocopy of the passport bio page.','Copies of previous Schengen visas (if applicable).']},
 {n:'02',title:'Photograph & Application',items:['Two recent passport-size colour photographs as per Schengen visa specifications.','Completed Schengen Visa Application Form.','Signed visa declaration form (if applicable).']},
 {n:'03',title:'Employment / Business Documents',items:['Company covering letter mentioning designation, salary, purpose of travel, and approved leave.','Employment ID card or employment proof.','For self-employed applicants: GST Registration, Company Registration Certificate, Partnership Deed, or Business Proof.']},
 {n:'04',title:'Financial Documents',items:['Personal bank statements for the last 6 months.','Income Tax Returns (ITR) for the last 2–3 assessment years.','Salary slips for the last 3 months or proof of regular income.','Proof of sufficient funds for the entire stay.']},
 {n:'05',title:'Travel Documents',items:['Confirmed return flight reservation.','Complete day-wise travel itinerary.','Hotel booking confirmations for the entire stay.','Valid travel medical insurance covering a minimum of EUR 30,000 throughout the Schengen Area.']},
 {n:'06',title:'Supporting Documents',items:['Invitation letter from a host in a Schengen country (if applicable).','Proof of relationship with the inviter (if visiting family or friends).','Personal cover letter explaining the purpose of travel.','Any additional supporting documents requested by the respective Embassy or Consulate.']}
];
const countries=['Austria 🇦🇹','Belgium 🇧🇪','Bulgaria 🇧🇬','Croatia 🇭🇷','Czech Republic 🇨🇿','Denmark 🇩🇰','Estonia 🇪🇪','Finland 🇫🇮','France 🇫🇷','Germany 🇩🇪','Greece 🇬🇷','Hungary 🇭🇺','Iceland 🇮🇸','Italy 🇮🇹','Latvia 🇱🇻','Liechtenstein 🇱🇮','Lithuania 🇱🇹','Luxembourg 🇱🇺','Malta 🇲🇹','Netherlands 🇳🇱','Norway 🇳🇴','Poland 🇵🇱','Portugal 🇵🇹','Romania 🇷🇴','Slovakia 🇸🇰','Slovenia 🇸🇮','Spain 🇪🇸','Sweden 🇸🇪','Switzerland 🇨🇭'];
export default function SchengenVisa(){
 return <><SEO title="Schengen Tourist Visa Assistance" description="Schengen tourist visa documentation assistance from Tourswale with ₹9,500 onwards visa charges and 15–20 working day processing guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'Schengen Tourist Visa Assistance',offers:{'@type':'Offer',price:'9500',priceCurrency:'INR'},provider:{'@type':'TravelAgency',name:'Tourswale'}}}/>
 <section className="visa-hero schengen-visa-hero"><div><Breadcrumbs items={['Visa Services','Schengen Tourist Visa']}/><span className="eyebrow">Fast • Reliable • Hassle-Free</span><h1>Schengen<br/>Tourist Visa</h1><p>Professional assistance for Indian travellers visiting one or multiple Schengen countries in Europe for tourism, family visits, sightseeing, cruises, and short-term leisure travel with complete visa documentation guidance.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><Clock/><span>Processing guidance</span><strong>15–20 Working Days</strong><small>Approximate processing time</small><hr/><span>Visa charges</span><strong>₹9,500 onwards</strong><small>Subject to visa category and fees</small></aside></section>
 <section className="section schengen-countries" style={{padding:'4rem 8vw',background:'#fff'}}><div style={{maxWidth:'1200px'}}><span className="eyebrow dark-eye">29 European Countries</span><h2 style={{fontSize:'2.5rem',margin:'0.5rem 0 2rem'}}>Countries Covered Under the Schengen Visa</h2><p style={{marginBottom:'2rem',fontSize:'1.1rem',color:'#4a5568'}}>A <strong>Schengen Visa</strong> allows you to travel across <strong>29 European countries</strong> with a single visa (subject to visa validity and entry conditions).</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(180px, 1fr))',gap:'1rem'}}>{countries.map(c=><div key={c} style={{padding:'0.8rem 1rem',background:'var(--ivory)',borderRadius:'4px',border:'1px solid #e2e8f0',fontSize:'0.95rem'}}>{c}</div>)}</div></div></section>
 <section className="section visa-intro" style={{background:'var(--ivory)'}}><div><span className="eyebrow dark-eye">Tourist visa checklist</span><h2>Documents Required</h2></div><p>Prepare complete and accurate documents supporting your travel purpose, financial capability, accommodation, travel insurance, and return plans. The Embassy or Consulate of the main Schengen destination may request additional documentation depending on the applicant's profile.</p></section>
 <section className="section visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3><ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="section" style={{padding:'4rem 8vw',background:'var(--ivory)',borderTop:'1px solid #e2e8f0'}}><div style={{maxWidth:'900px'}}><div style={{display:'flex',alignItems:'center',gap:'1rem',marginBottom:'1.5rem'}}><Info style={{color:'var(--gold)',width:'30px',height:'30px'}}/><h2 style={{fontSize:'2rem',margin:0}}>Important Application Information</h2></div><ul style={{listStyle:'none',padding:0,display:'grid',gap:'1rem'}}><li style={{display:'flex',gap:'1rem',alignItems:'flex-start'}}><Check style={{color:'var(--gold)',flexShrink:0,marginTop:'4px'}}/> <p style={{margin:0,fontSize:'1.05rem',lineHeight:1.6}}>Apply through the <strong>Embassy or Consulate of the country where you will spend the longest duration</strong> during your trip.</p></li><li style={{display:'flex',gap:'1rem',alignItems:'flex-start'}}><Check style={{color:'var(--gold)',flexShrink:0,marginTop:'4px'}}/> <p style={{margin:0,fontSize:'1.05rem',lineHeight:1.6}}>If your stay is equally divided between multiple Schengen countries, apply through the <strong>country where you will first enter the Schengen Area</strong>.</p></li><li style={{display:'flex',gap:'1rem',alignItems:'flex-start'}}><Check style={{color:'var(--gold)',flexShrink:0,marginTop:'4px'}}/> <p style={{margin:0,fontSize:'1.05rem',lineHeight:1.6}}>A Schengen Visa generally permits travel across all participating Schengen countries during its validity, subject to the conditions stated on the visa.</p></li></ul></div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>15–20 Working Days</h2><p>Processing periods are approximate and may vary depending on the Embassy/Consulate and applicant profile.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the respective Schengen Embassy or Consulate. Submission of complete documents does not guarantee visa approval.</p><p>Visa fees, processing timelines, documentation requirements, travel insurance requirements, biometric requirements, and entry regulations are subject to change without prior notice. Applicants are advised to reconfirm the latest requirements before submission.</p></div></section>
 <section className="visa-benefits"><div><span>Service benefits</span><h2>Your European Trip<br/>Starts Here.</h2></div><div>{['Expert visa guidance','Complete documentation support','Quick processing assistance','Trusted travel partner','Personalised application review','Dedicated Tourswale support'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Prepare Your Schengen Application.</h2><p>Speak with our visa team before sharing documents so we can explain the correct submission process.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}
