import {Check,Clock,FileText,ShieldCheck,Phone,MessageCircle,Mail} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const groups=[
 {n:'01',title:'Passport',items:['Clear scan of the front and last pages','Minimum six months’ validity from the travel date']},
 {n:'02',title:'Photograph',items:['Recent passport-size photograph','White background','High-resolution image']},
 {n:'03',title:'Financial Documents',items:['Personal bank statement for the last three months','Updated and stamped by the bank, if available']},
 {n:'04',title:'Travel Documents',items:['Confirmed return flight tickets','Hotel reservation or accommodation details','Travel itinerary']},
 {n:'05',title:'Personal Information',items:['Active mobile number','WhatsApp number','Email ID','Residential address']},
 {n:'06',title:'Employment or Business Proof',sub:[['Salaried Applicants',['Employment ID card','Leave approval letter','Last three months’ salary slips']],['Self-Employed Applicants',['GST certificate','Business registration','Company visiting card']]]},
 {n:'07',title:'Additional Documents',sub:[['For Minors',['Birth certificate','Passport copies of parents']],['For Married Couples',['Marriage certificate, if required']]]}
];
export default function Visa(){
 return <><SEO title="Singapore Tourist Visa Assistance" description="Singapore tourist visa assistance from Tourswale with a complete document checklist, 3–5 working day processing guidance and dedicated support." schema={{'@context':'https://schema.org','@type':'Service',name:'Singapore Tourist Visa Assistance',provider:{'@type':'TravelAgency',name:'Tourswale'},areaServed:'India'}}/>
 <section className="visa-hero"><div><Breadcrumbs items={['Visa Services','Singapore Tourist Visa']}/><span className="eyebrow">Dream It. Pack It. Tourswale It.</span><h1>Singapore<br/>Tourist Visa</h1><p>Explore the best of Singapore with clear documentation guidance and dedicated assistance from submission to decision.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> Start on WhatsApp</a><a className="button light" href="tel:+919987561143"><Phone/> Call Visa Expert</a></div></div><aside><ShieldCheck/><span>Visa processing guidance</span><strong>3–5 Working Days</strong><small>Approximate processing time</small></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Document checklist</span><h2>Everything You Need,<br/>Clearly Explained.</h2></div><p>Please provide the following clear, valid and up-to-date documents for smooth visa processing. Additional documents may be requested depending on the applicant’s profile.</p></section>
 <section className="section ivory visa-documents"><div className="document-grid">{groups.map(g=><article key={g.n}><b>{g.n}</b><FileText/><h3>{g.title}</h3>{g.items&&<ul>{g.items.map(x=><li key={x}><Check/>{x}</li>)}</ul>}{g.sub&&g.sub.map(([title,items])=><div className="document-sub" key={title}><h4>{title}</h4><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul></div>)}</article>)}</div></section>
 <section className="section visa-notice"><div><Clock/><span>Processing time</span><h2>3–5 Working Days</h2><p>This is an approximate processing period and may vary depending on immigration review, holidays, document quality and individual circumstances.</p></div><div><h2>Please Note</h2><p>Visa approval is solely at the discretion of the Singapore Immigration Authorities. Submission of complete documents does not guarantee visa approval.</p><p>All documents must be clear, valid and up to date. Tourswale provides application and documentation assistance but cannot influence the final decision.</p></div></section>
 <section className="visa-benefits"><div><span>Why choose Tourswale?</span><h2>Guidance You Can<br/>Travel Confidently With.</h2></div><div>{['Safe and secure handling','Hassle-free process','Quick processing support','Dedicated assistance','Customised travel solutions','24×7 travel support'].map(x=><p key={x}><Check/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Visa assistance</span><h2>Ready to Begin?</h2><p>Send your documents securely after speaking with our visa specialist.</p></div><div><a href="tel:+919987561143"><Phone/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="mailto:info@tourswale.com"><Mail/><span>Email<b>info@tourswale.com</b></span></a><div><ShieldCheck/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}