import {Link} from 'react-router-dom';
import {ArrowRight,Check,Clock,FileCheck,Globe2,GraduationCap,BriefcaseBusiness,Users,Plane,ShieldCheck,MessageCircle,Phone} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const assistance=[[Plane,'Tourist Visa'],[BriefcaseBusiness,'Business Visa'],[GraduationCap,'Student Visa'],[Users,'Visitor & Family Visa'],[Clock,'Transit Visa'],[Globe2,'Other US Visa Guidance']];
export default function USVisa(){
 return <><SEO title="US Tourist Visa Assistance" description="US tourist visa assistance from Tourswale with application guidance, documentation support and appointment preparation for travellers from India." schema={{'@context':'https://schema.org','@type':'Service',name:'US Tourist Visa Assistance',provider:{'@type':'TravelAgency',name:'Tourswale'},areaServed:'India'}}/>
 <section className="us-visa-hero"><div><Breadcrumbs items={['Visa Services','US Tourist Visa']}/><span className="eyebrow">Your Journey, Our Priority</span><h1>Dream. Explore.<br/><em>Experience America.</em></h1><p>We help make your USA visa application simple and organised through clear guidance, document preparation and appointment support.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> WhatsApp Visa Expert</a><a className="button light" href="tel:+919987561143"><Phone/> Call Now</a></div></div><aside><Clock/><span>Appointment assistance</span><strong>Urgent Appointment Guidance</strong><p>Available only for eligible emergency or expedited cases and always subject to US consular rules and appointment availability.</p><Link to="/contact">Discuss eligibility <ArrowRight/></Link></aside></section>
 <section className="section visa-intro"><div><span className="eyebrow dark-eye">Tourswale visa support</span><h2>You Focus on the Journey.<br/>We’ll Guide the Process.</h2></div><p>Our team helps you understand the applicable application stages, organise supporting information and prepare confidently. Final eligibility, appointment allocation and visa approval remain solely with US authorities.</p></section>
 <section className="section ivory"><div className="us-assist-grid">{assistance.map(([I,h])=><article key={h}><I/><h3>{h}</h3><p>Personalised guidance based on your travel purpose and applicant profile.</p><Link to="/contact">Request assistance <ArrowRight/></Link></article>)}</div></section>
 <section className="visa-benefits"><div><span>Why choose Tourswale?</span><h2>Prepared Applications.<br/>Confident Travellers.</h2></div><div>{['Expert visa guidance','Complete documentation support','Efficient application preparation','Personalised applicant review','Trusted travel partner','Dedicated assistance'].map(x=><p key={x}><FileCheck/>{x}</p>)}</div></section>
 <section className="section visa-notice"><div><ShieldCheck/><span>Important notice</span><h2>Approval Is Never Guaranteed</h2><p>US visa approval and appointment decisions are made solely by the US Embassy, Consulate and relevant government authorities.</p></div><div><h2>Appointment Support</h2><p>Urgent or expedited appointments may be requested only when the applicant meets current official criteria. Tourswale can guide the request process but cannot guarantee availability or approval.</p><p>Applicants should never make non-refundable travel commitments until a visa is issued.</p></div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Start Your USA<br/>Visa Journey.</h2><p>Thousands of travellers rely on structured guidance to prepare with greater clarity and confidence.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>Call / WhatsApp<b>+91 99875 61143</b></span></a><a href="https://www.tourswale.com"><Globe2/><span>Website<b>www.tourswale.com</b></span></a><div><ShieldCheck/><span>Location<b>New Seawoods, Navi Mumbai</b></span></div></div></section><CTA/></>
}