import {Link} from 'react-router-dom';
import {ArrowRight,BriefcaseBusiness,GraduationCap,Plane,ShieldCheck,Users,Globe2,Clock,MessageCircle,Phone,Check} from 'lucide-react';
import {SEO,Breadcrumbs,CTA} from '../components';
const visaTypes=[[Plane,'Tourist Visa','For holidays, sightseeing and short personal visits.'],[BriefcaseBusiness,'Business Visa','For meetings, conferences and professional travel.'],[GraduationCap,'Student Visa','Guidance for study applications and education travel.'],[Globe2,'Work Visa','Documentation assistance for employment abroad.'],[Users,'Family Visa','Support for family visits and dependent applications.'],[Clock,'Transit Visa','Short-stay guidance for eligible transit journeys.']];
const countries=['USA','Canada','United Kingdom','Schengen Countries (Europe)','Australia','New Zealand','Japan','South Korea','Singapore','Malaysia','Thailand','Dubai / UAE','Qatar','Saudi Arabia','Oman','Türkiye','China','Hong Kong','Indonesia','Vietnam','Philippines','Mauritius','Egypt','Sri Lanka'];
export default function Visa(){
 return <><SEO title="Visa Services for 50+ Countries" description="Tourswale provides tourist, business, student, work, family and transit visa assistance with documentation support and personalised guidance." schema={{'@context':'https://schema.org','@type':'Service',name:'International Visa Assistance',provider:{'@type':'TravelAgency',name:'Tourswale'},areaServed:'India'}}/>
 <section className="visa-hub-hero"><div><Breadcrumbs items={['Visa Services']}/><span className="eyebrow">Your Journey, Our Priority</span><h1>Your Dream Destination,<br/><em>We Make It Possible.</em></h1><p>Clear documentation support and personalised visa guidance for travellers, families, students and professionals across India.</p><div className="button-row"><a className="button gold" href="https://wa.me/919987561143"><MessageCircle/> WhatsApp Visa Expert</a><a className="button light" href="tel:+919987561143"><Phone/> Call Now</a></div></div><div className="visa-trust">{[['Fast processing','Responsive application support'],['Expert guidance','Help at every document stage'],['50+ countries','Wide international coverage']].map(([h,p])=><div key={h}><Check/><strong>{h}</strong><span>{p}</span></div>)}</div></section>
 <section className="section"><div className="section-heading"><span>What we assist with</span><h2>Our Visa Services</h2><p>Choose the category that matches your travel purpose. Requirements and processing periods vary by destination and applicant profile.</p></div><div className="visa-type-grid">{visaTypes.map(([I,h,p])=><article key={h}><I/><h3>{h}</h3><p>{p}</p><Link to="/contact">Request guidance <ArrowRight/></Link></article>)}</div></section>
 <section className="section ivory country-visas"><div><span className="eyebrow dark-eye">Global coverage</span><h2>Visas for Major Countries</h2><p>Tourswale assists with visa documentation for more than 50 destinations. Availability depends on current consular rules and applicant eligibility.</p><Link className="button dark" to="/visa-services/singapore">View Singapore Visa Checklist <ArrowRight/></Link></div><div className="country-list">{countries.map((x,i)=>x==="Japan"?<Link className="country-link" to="/visa-services/japan-business" key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}<ArrowRight/></Link>:<span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}<span className="more-countries"><b>+</b>And many more</span></div></section>
 <section className="visa-benefits"><div><span>Why choose Tourswale?</span><h2>Documentation,<br/>Done Thoughtfully.</h2></div><div>{['Visa assistance for over 50 countries','Complete documentation support','Personalised guidance','Safe, secure and reliable service','Dedicated application assistance','Current requirement guidance'].map(x=><p key={x}><ShieldCheck/>{x}</p>)}</div></section>
 <section className="section visa-contact"><div><span className="eyebrow dark-eye">Contact Tourswale</span><h2>Explore the World<br/>with Tourswale.</h2><p>Speak with our visa team before sending documents. We’ll explain the applicable requirements and next steps.</p></div><div><a href="https://wa.me/919987561143"><MessageCircle/><span>WhatsApp for details<b>+91 99875 61143</b></span></a><a href="tel:+919987561143"><Phone/><span>Call our team<b>+91 99875 61143</b></span></a><div><Globe2/><span>Office<b>Shop No. 1, Plot No. 67, Hari Om CHS,<br/>Sector 50, New Seawoods,<br/>Navi Mumbai – 400706</b></span></div></div></section><CTA/></>
}