import {useEffect,useRef,useState} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowRight,Clock,Camera,Menu,MessageCircle,Phone,Plus,Send,X} from 'lucide-react';
import {gsap} from 'gsap'; import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {faqs} from './data';
gsap.registerPlugin(ScrollTrigger);
export const money=n=>new Intl.NumberFormat('en-IN').format(n);
export function Reveal({children,className=''}){const ref=useRef();useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const a=gsap.fromTo(ref.current,{y:40,opacity:0},{y:0,opacity:1,duration:.9,ease:'power3.out',scrollTrigger:{trigger:ref.current,start:'top 88%'}});return()=>a.kill()},[]);return <div ref={ref} className={className}>{children}</div>}
export function Header(){const [open,setOpen]=useState(false),[solid,setSolid]=useState(false);const loc=useLocation();useEffect(()=>setOpen(false),[loc]);useEffect(()=>{const f=()=>setSolid(scrollY>30);addEventListener('scroll',f);f();return()=>removeEventListener('scroll',f)},[]);const links=[['/','Home'],['/domestic-tours','Domestic Tours'],['/international-tours','International Tours'],['/tour-packages','Tour Packages'],['/about','About Us'],['/insights','Travel Insights'],['/contact','Contact']];return <header className={`header ${solid||open?'solid':''}`}><Link className="logo" to="/">Tourswale<span>Journeys designed around you</span></Link><nav>{links.map(([u,l])=><NavLink key={u} to={u}>{l}</NavLink>)}</nav><Link to="/contact" className="button gold header-cta">Plan My Trip</Link><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button>{open&&<div className="mobile-nav">{links.map(([u,l])=><NavLink key={u} to={u}>{l}</NavLink>)}<Link to="/contact" className="button gold">Plan My Trip</Link></div>}</header>}
export function Footer(){return <footer><div className="footer-top"><div><Link className="logo" to="/">Tourswale<span>Journeys designed around you</span></Link><p>Thoughtfully designed domestic and international holidays for travellers across India.</p><div className="social"><Camera/><MessageCircle/></div></div><div><h4>Explore India</h4>{['Kashmir','Rajasthan','Kerala','Ladakh','Andaman'].map(x=><Link to="/domestic-tours" key={x}>{x}</Link>)}</div><div><h4>Across the world</h4>{['Europe','Japan','Bali','Dubai','USA'].map(x=><Link to="/international-tours" key={x}>{x}</Link>)}</div><div><h4>Stay inspired</h4><p>Travel notes and considered ideas, delivered occasionally.</p><label className="newsletter"><span className="sr-only">Email address</span><input type="email" placeholder="Your email address"/><button aria-label="Subscribe"><Send/></button></label><p className="contact-line">+91 98765 43210<br/>hello@tourswale.in</p></div></div><div className="footer-base"><span>© 2026 Tourswale. All rights reserved.</span><div><Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms">Terms & Conditions</Link></div></div></footer>}
export function SEO({title,description,schema}){return <><title>{title} | Tourswale</title><meta name="description" content={description}/><link rel="canonical" href={`https://www.tourswale.in${location.pathname}`}/><meta property="og:title" content={`${title} | Tourswale`}/><meta property="og:description" content={description}/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary_large_image"/>{schema&&<script type="application/ld+json">{JSON.stringify(schema)}</script>}</>}
export function SectionHeading({eyebrow,title,text,light=false}){return <div className={`section-heading ${light?'light':''}`}><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function TourCard({tour}){return <article className="tour-card"><Link to={`/tours/${tour.slug}`} className="card-image"><img loading="lazy" src={tour.image} alt={`${tour.title} travel experience`}/><span>{tour.location}</span></Link><div className="card-body"><div className="tour-meta"><span><Clock/> {tour.days} Days</span><span>From <b>₹{money(tour.price)}</b></span></div><h3><Link to={`/tours/${tour.slug}`}>{tour.title}</Link></h3><p>{tour.desc}</p><div className="card-foot"><div>{tour.tags.map(t=><small key={t}>{t}</small>)}</div><Link aria-label={`View ${tour.title}`} to={`/tours/${tour.slug}`}><ArrowRight/></Link></div></div></article>}
export function CTA(){return <section className="final-cta"><div><span>Let’s create something memorable</span><h2>Your Next Journey<br/>Starts Here.</h2></div><div><p>Tell us where you want to go, and our travel specialists will create a holiday that feels entirely yours.</p><div className="button-row"><Link className="button gold" to="/contact">Plan My Trip <ArrowRight/></Link><a className="button outline" href="tel:+919876543210"><Phone/> Call Our Travel Expert</a></div></div></section>}
export function Breadcrumbs({items}){return <div className="breadcrumbs"><Link to="/">Home</Link>{items.map((x,i)=><span key={x}>/ {i===items.length-1?x:<Link to="#">{x}</Link>}</span>)}</div>}
export function FAQ({items=faqs}){const [open,setOpen]=useState(0);return <div className="faq">{items.map(([q,a],i)=><div className={open===i?'open':''} key={q}><button onClick={()=>setOpen(open===i?-1:i)}><span>{q}</span><Plus/></button><p>{a}</p></div>)}</div>}
export function EnquiryForm({compact=false}){return <form className={`enquiry ${compact?'compact':''}`} onSubmit={e=>e.preventDefault()}><div className="field-grid"><label>Full name<input required placeholder="Your full name"/></label><label>Email<input required type="email" placeholder="you@email.com"/></label><label>Phone number<input required type="tel" placeholder="+91"/></label><label>Preferred destination<input placeholder="Where would you like to go?"/></label><label>Holiday type<select><option>Domestic</option><option>International</option><option>Not sure yet</option></select></label><label>Number of travellers<input type="number" min="1" placeholder="2"/></label>{!compact&&<><label>Approximate travel date<input type="date"/></label><label>Trip duration<input placeholder="e.g. 7 days"/></label><label>Estimated budget in INR<select><option>₹30,000–₹60,000</option><option>₹60,000–₹1,00,000</option><option>₹1,00,000–₹2,00,000</option><option>₹2,00,000+</option></select></label><label>Travel style<select><option>Leisure</option><option>Honeymoon</option><option>Family</option><option>Luxury</option><option>Adventure</option></select></label><label className="full">Tell us about your trip<textarea rows="4" placeholder="The kind of holiday you have in mind…"/></label><label className="check full"><input type="checkbox" required/> I agree to be contacted about my enquiry and accept the privacy policy.</label></>}</div><button className="button gold" type="submit">Send My Enquiry <ArrowRight/></button></form>}
export function WhatsApp(){return <a className="whatsapp" href="https://wa.me/919876543210" aria-label="Chat with Tourswale on WhatsApp"><MessageCircle/></a>}
export function ScrollTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});},[pathname]);return null}
