export const images={hero:'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=2200&q=85',kashmir:'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80',rajasthan:'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',kerala:'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',ladakh:'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',andaman:'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80',himachal:'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',switzerland:'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',italy:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=80',japan:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80',bali:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',dubai:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',singapore:'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',turkiye:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80',usa:'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=1200&q=80'};
export const domestic=[
 {slug:'kashmir-signature-escape',title:'Kashmir Signature Escape',location:'Kashmir',days:6,price:38999,image:images.kashmir,desc:'Shikara mornings, alpine valleys and warm Kashmiri hospitality.',tags:['Dal Lake','Gulmarg']},
 {slug:'royal-rajasthan-journey',title:'Royal Rajasthan Journey',location:'Rajasthan',days:7,price:44999,image:images.rajasthan,desc:'Palace stays, desert sunsets and stories of living heritage.',tags:['Jaipur','Jaisalmer']},
 {slug:'kerala-backwater-retreat',title:'Kerala Backwater Retreat',location:'Kerala',days:6,price:36500,image:images.kerala,desc:'Tea country, tranquil waterways and coastal flavours.',tags:['Munnar','Alleppey']},
 {slug:'ladakh-adventure',title:'Ladakh High-Altitude Adventure',location:'Ladakh',days:7,price:48999,image:images.ladakh,desc:'Otherworldly passes, blue lakes and mountain monasteries.',tags:['Pangong','Nubra']},
 {slug:'andaman-getaway',title:'Andaman Island Getaway',location:'Andaman',days:5,price:42500,image:images.andaman,desc:'Pristine beaches and unhurried island days.',tags:['Havelock','Snorkelling']},
 {slug:'himachal-escape',title:'Himachal Mountain Escape',location:'Himachal Pradesh',days:6,price:31999,image:images.himachal,desc:'Pine forests, mountain cafés and quiet Himalayan trails.',tags:['Manali','Solang']}
];
export const international=[
 {slug:'switzerland-paris',title:'Switzerland & Paris',location:'Europe',days:9,price:189999,image:images.switzerland,desc:'Alpine rail journeys followed by the romance of Paris.',tags:['Lucerne','Paris']},
 {slug:'italy-heritage',title:'Italy Heritage Journey',location:'Europe',days:8,price:174999,image:images.italy,desc:'Art, architecture and timeless Italian cities.',tags:['Rome','Venice']},
 {slug:'japan-discovery',title:'Japan Cultural Discovery',location:'Asia',days:8,price:159999,image:images.japan,desc:'Ancient rituals and electric cityscapes in perfect balance.',tags:['Tokyo','Kyoto']},
 {slug:'bali-luxury',title:'Bali Luxury Escape',location:'Asia',days:6,price:74999,image:images.bali,desc:'Rice terraces, temple mornings and refined island stays.',tags:['Ubud','Nusa Dua']},
 {slug:'dubai-abu-dhabi',title:'Dubai & Abu Dhabi',location:'Middle East',days:6,price:69999,image:images.dubai,desc:'Future-facing cities, desert evenings and iconic hospitality.',tags:['Dubai','Abu Dhabi']},
 {slug:'singapore-malaysia',title:'Singapore & Malaysia',location:'Asia',days:7,price:89999,image:images.singapore,desc:'Sleek skylines, gardens and a vibrant culinary trail.',tags:['Singapore','Kuala Lumpur']},
 {slug:'turkiye-highlights',title:'Türkiye Highlights',location:'Middle East',days:8,price:114999,image:images.turkiye,desc:'Bazaars, minarets and Cappadocia skies.',tags:['Istanbul','Cappadocia']},
 {slug:'new-york-experience',title:'New York City Experience',location:'USA',days:7,price:179999,image:images.usa,desc:'Landmark neighbourhoods and the energy of Manhattan.',tags:['Manhattan','Brooklyn']}
];
export const allTours=[...domestic,...international];
export const articles=[
 {slug:'best-time-europe-india',title:'Best Time to Visit Europe from India',category:'Seasonal guide',time:'7 min read',image:images.switzerland,intro:'A practical month-by-month guide to weather, value and memorable European experiences.'},
 {slug:'first-time-kashmir-guide',title:'A Complete First-Time Guide to Kashmir',category:'India',time:'6 min read',image:images.kashmir,intro:'What to see, when to go and how to plan a seamless first journey to the valley.'},
 {slug:'dubai-tips-indian-tourists',title:'Dubai Travel Tips for Indian Tourists',category:'Travel advice',time:'5 min read',image:images.dubai,intro:'Useful entry, currency, etiquette and neighbourhood tips for a confident Dubai holiday.'}
];
export const testimonials=[{quote:'Every transfer, hotel and little surprise felt considered. Switzerland was effortless from the moment we landed.',name:'Ananya & Rohan',place:'Pune · Switzerland'},{quote:'Our parents and children both loved Kashmir. Tourswale balanced comfort with experiences beautifully.',name:'The Mehta Family',place:'Ahmedabad · Kashmir'},{quote:'They understood our pace and created a Bali honeymoon that felt genuinely personal.',name:'Ishita & Karan',place:'Delhi · Bali'}];
export const faqs=[['Can Tourswale customise every itinerary?','Yes. Dates, hotels, pace and experiences can all be shaped around your preferences and budget.'],['Do you arrange both Indian and international holidays?','Yes. We plan domestic journeys across India and international holidays across Europe, Asia, the Middle East and the USA.'],['Are flights included in displayed prices?','Package inclusions vary. Your final proposal clearly itemises flights, stays, transfers, experiences and taxes.'],['How early should I enquire?','For the best choice, enquire 8–12 weeks ahead for international trips and 4–8 weeks ahead for domestic travel.']];
